#!/bin/bash
# ******************************************************************************
# *   Copyright (c) 2025 Aumovio, Inc., all rights reserved
# *   All material contained herein is CONTINENTAL CONFIDENTIAL and PROPRIETARY.
# *   Any reproduction of this material without written consent from
# *   Continental Automotive Systems, Inc. is strictly forbidden.
# *
# *   Filename: sbom_artifacts.sh
# *
# *   Description: This script is responsible of verify and copy the files
# *                generated by the SBOM analysis/execution
# *
# ******************************************************************************
SCRIPT_NAME=$(basename "${0}")
LOGFILE=$(dirname $0)/"${SCRIPT_NAME%.*}.log"
echo "LOGGING to ${LOGFILE}"
exec > >(tee "${LOGFILE}");

# ----------------------------------------------------------- #
# All output from commands in this block sent to file $LOGFILE.
echo "START: ${SCRIPT_NAME} $(date)"

## Script Parameters
WORKSPACE=${1?workspaces is required}
BASELINE_NAME=${2?baseline_name is required}

## Script Variables
fetch_cbins=("folders.json")
elfscan_files=( "about_report.json" "depends.json" "elf_report.json" "foss.csv" "foss.xlsx" "othersdb.json" )
fetch_cbins_output="${WORKSPACE}/fetch_cbins_output.tar.gz"
elfscan_files_output="${WORKSPACE}/elfscan_files_output.tar.gz"
osrb_bundle_tar="${WORKSPACE}/release_for_osrb.tar.gz"
# shared drive variables
RGB_SHARED_DRIVE="//automotive-wan.com/root/smt/did01665/ConMod/18_Software_builds_AudiConMod"
MOUNTING_DIR="${WORKSPACE}/conmod_shared_drive"
FOSS_STAGING_DIR="${MOUNTING_DIR}/FOSS"
# State variables
RET_CODE=0

## Import external libraries
echo "Import external libraries"
source "${WORKSPACE}/conmod-cm/utils/platform-common.lib"

echo "##################################################################"
echo "                               DETAILS"
echo
echo
echo "WORKSPACE:            ${WORKSPACE}"
echo "BASELINE_NAME:        ${BASELINE_NAME}"
echo
echo

verificator() {
    #list_of_files -> array param

    # As argument is an array, it should be like this.
    list_of_files=("$@")
    header4 "Output files verification: ${list_of_files[@]}"
    for output_file in ${list_of_files[@]}; do
        [[ ! -f ${output_file} ]] && bail "${output_file} Not Found!"
    done
}

tar_creator() {
    #tar_name -> string param
    #shift -> to remove first param and then take the array
    #tar_files -> array param

    tar_name="$1" && shift
    tar_files=("$@")
    output_name=$(echo "${tar_name}" | rev | cut -d"/" -f1 | rev)
    header4 "Generating ${output_name}"
    tar cvzf "${tar_name}" "${tar_files[@]}"
    RET_CODE=$((RET_CODE + $?))
    [[ ${RET_CODE} -ne 0 ]] && bail "Not possible to generate ${tar_name}"
}

header1 "Generating output tar files"

# Verification & tar file creation
# fetch_cbins
verificator "${fetch_cbins[@]}"
tar_creator "${fetch_cbins_output}" "${fetch_cbins[@]}"
# elfscan_files
verificator "${elfscan_files[@]}"
tar_creator "${elfscan_files_output}" "${elfscan_files[@]}"

# Creating folder for mount wetzlar shared drive
header2 "Creating mount point for wetzlar share drive"
echo "mkdir -p ${MOUNTING_DIR}"
mkdir -p ${MOUNTING_DIR}
RET_CODE=$((RET_CODE + $?))

header2 "Mounting wetzlar shared drive"
# FIXME: This is a temporary solution for save official conmod baselines
echo "mount.cifs -o credentials=/home/uidg4627/.credentials/dpfil02,uid=uidg4627,gid=uidg4627 ${RGB_SHARED_DRIVE} ${MOUNTING_DIR}"
sudo mount.cifs -o credentials=/home/uidg4627/.credentials/dpfil02,uid=uidg4627,gid=uidg4627 "${RGB_SHARED_DRIVE}" "${MOUNTING_DIR}"
RET_CODE=$((RET_CODE + $?))
[[ ${RET_CODE} -ne 0 ]] && bail "Mounting ${RGB_SHARED_DRIVE} drive failed"

# Folder creation
if [[ ! -d "${FOSS_STAGING_DIR}/${BASELINE_NAME}" ]]; then
  header2 "Creating staging folder in -> ${FOSS_STAGING_DIR}/${BASELINE_NAME}"
  echo "> mkdir -p ${FOSS_STAGING_DIR}${BASELINE_NAME}"
  mkdir -p "${FOSS_STAGING_DIR}/${BASELINE_NAME}"
  RET_CODE=$((RET_CODE + $?))
  [[ ${RET_CODE} -ne 0 ]] && bail "Create ${FOSS_STAGING_DIR}/${BASELINE_NAME} folder failed"
fi

header2 "Storing Output Artifacts"
# copying cbins
cp -pv "${fetch_cbins_output}" "${FOSS_STAGING_DIR}/${BASELINE_NAME}"
RET_CODE=$((RET_CODE + $?))
# copying elfscan
cp -pv "${elfscan_files_output}" "${FOSS_STAGING_DIR}/${BASELINE_NAME}"
RET_CODE=$((RET_CODE + $?))
[[ ${RET_CODE} -ne 0 ]] && bail "Copying artifacts failed"

if [[ ${osrb_bundle_tar} ]]; then
  header2 "Copying osrb bundle file - release_for_osrb.tar.gz"
  cp -pv "${osrb_bundle_tar}" "${FOSS_STAGING_DIR}/${BASELINE_NAME}"
  RET_CODE=$((RET_CODE + $?))
  [[ ${RET_CODE} -ne 0 ]] && bail "Copying release_for_osrb.tar.gz failed"
fi

header2 "Unmount wetzlar shared drive"
sudo umount "${MOUNTING_DIR}"
RET_CODE=$((RET_CODE + $?))
[[ ${RET_CODE} -ne 0 ]] && echo "WARNING: unable to unmount shared drive, please verify the host machine"

echo "# ----------------------------------------------------------- #"
echo "END: $(basename $0) [${RET_CODE}]: $(date)"
