#!/usr/bin/python
"""
# ******************************************************************************
# *
# *   (c) 2026 Aumovio, Inc., all rights reserved
# *
# *   All material contained herein is CONTINENTAL CONFIDENTIAL and PROPRIETARY.
# *   Any reproduction of this material without written consent from
# *   Continental Automotive Systems, Inc. is strictly forbidden.
# *
# *   Filename:     abi_contract_validator.py
# *
# *   Description:  Validate contract file generated by abi_contract_generator.py.
# *                 Define deviations in:
# *                       - Toolchain Libraries
# *                       - minimum required versions
# *                       - Telux Headers
# *
# *****************************************************************************
"""
# Imports
import os
import sys
import json
import subprocess
# For diff, DeepDiff should be installed (pip3 install deepdiff)
from deepdiff import DeepDiff
from pprint import pprint

# Adding new Path
currentdir =os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)

# Conmod utils
from cmlib import util

## Script Variables
workspace = sys.argv[1]
cmp_file = sys.argv[2]
ref_file = os.path.join(currentdir,"abi_ref_contract.json")

# Files exist??
for f in cmp_file, ref_file:
    if not os.path.isfile(f) :
        print("{} not found".format(f))
        exit(1)

util.header("")

util.header2("Reading reference file {}".format(ref_file))
# Charging reference file to Dict
with open(ref_file, 'r') as ref_file:
    r_file = json.load(ref_file)

util.header2("Reading comparison file {}".format(cmp_file))
# Comparison file to Dict
with open(cmp_file, 'r') as cmp_file:
    c_file = json.load(cmp_file)

util.header3("Removing metadata information (date)")
# Removing Date information from Dict
r_file["metadata"].pop("generated")
c_file["metadata"].pop("generated")

util.header2("File comparison")
# Dict comparison
if (r_file == c_file):
    print("No changes")
else:
    util.header3("Changes Detected")
    pprint(DeepDiff(r_file, c_file), indent = 2)
