#!/bin/bash
# ******************************************************************************
# *   Copyright (c) 2024 Continental Automotive Systems, Inc., all rights reserved
# *   All material contained herein is CONTINENTAL CONFIDENTIAL and PROPRIETARY.
# *   Any reproduction of this material without written consent from
# *   Continental Automotive Systems, Inc. is strictly forbidden.
# *
# *   Filename: swl-test_generation.sh
# *
# *   Description: Secure copy of the artifacts generated by the
# *                delivery-artifact-collector and responsible for generation swdl test bundle
# *                Script responsible for generation of N-1 bundles
# *
# ******************************************************************************
SCRIPT_NAME=$(basename "${0}")
LOGFILE=$(dirname $0)/"${SCRIPT_NAME%.*}.log"
echo "LOGGING to ${LOGFILE}"
exec > >(tee "${LOGFILE}");

# ----------------------------------------------------------- #
# All output from commands in this block sent to file $LOGFILE.
echo "START: ${SCRIPT_NAME} $(date)"

# Arguments variables
WORKSPACE=${1?workspace is required}
BASELINE_NAME=${2?baseline_name is required}
RELEASE_ID=${3?release_id is required}
# space seperated list of bundle IDs, e.g. "X641 X646"
SWL_DOWNLOAD_BUNDLES=${4?swl_download_bundles is required}
FLAVOR=${5}

if [[ "$FLAVOR" == "" ]]; then
   FLAVOR="devel"
fi

# Script variables
#SCRIPT_DIR=$(dirname $(readlink -f $(basename $0)))
SHARED_DRIVE_TC="/u01/app/jenkins/documents"
SDK_FS="${WORKSPACE}/release/fs/$FLAVOR"
ISO_GENERATION_SCRIPT="${SDK_FS}/opt/conti/share/scripts/generate_swdl_blocks.py"
SET_ENV_SCRIPT="${SDK_FS}/opt/conti/share/scripts/set_env.sh"
STAGIN_DIR="${WORKSPACE}/SDK-STAGING"
PKG_ZIP="tp_sdk_${BASELINE_NAME}_pkg.zip"
SDK_BUNDLE_DIR="tp_sdk_${RELEASE_ID}_pkg"
EXTERNAL_PACKAGES_DIR="${WORKSPACE}/external_packages"

CONTI_IMAGE_DIR="${WORKSPACE}/release/images/${FLAVOR}/4K"
SWDL_IMAGE_DIR="${WORKSPACE}/release-eso"
EXTRACTED_BUNDLE_DIR="${WORKSPACE}/extracted_bundle"
EXTRACTED_BLOCKS_DIR="${WORKSPACE}/extracted_swdl_blocks"
EXTRACTED_ISOPKG_DIR="${WORKSPACE}/extracted_iso_package"
SWL_TEST_UPGRADE="swl-test/upgrade"
SWL_TEST_DOWNGRADE="swl-test/downgrade"
GENERATE_IMAGES_DIR="${WORKSPACE}/release-eso"
SWL_BUNDLE_NAME="swl-bundle.zip"
EXTERNAL_PACKAGES_NAME="external-packages.tgz"
SWL_RELEASES="conmod-swl"
RET_CODE=0

# Patterns
BLOCKS_PATTERN="*/*swdl_blocks.tgz"
CONTI_PACKAGE_TAR_PATTERN="10_conti*.tar.gz"
MODEM_PACKAGE_TAR_PATTERN="13_*.tar.gz"

# Import libraries
echo "Import external libraries"
source "${WORKSPACE}/.launchers/conmod-cm/utils/platform-common.lib"
source "${WORKSPACE}/.launchers/conmod-cm/utils/artifactory.lib"
source "${WORKSPACE}/.launchers/conmod-cm/sdk/sdk-common.inc"

# add 'all' feature
if [[ "${SWL_DOWNLOAD_BUNDLES}" == "all" ]]; then
  SWL_DOWNLOAD_BUNDLES=$(get_subfolder_list ${SWL_RELEASES} "")
  [[ $? -ne 0 ]] && bail "Error getting SWL_DOWNLOAD_BUNDLES for 'all'!"
fi
echo "Checking for SWL download bundles ${SWL_DOWNLOAD_BUNDLES[@]}..."
#first check if all input files exist...
for SWL_DOWNLOAD_BUNDLE in ${SWL_DOWNLOAD_BUNDLES[@]}
do
  # TODO: remove test
  artifactory_url="${ARTIFACTORY_SERVER}/${REPOSITORY}/${SWL_RELEASES}/${SWL_DOWNLOAD_BUNDLE}/"
  artifactory_path_exists "${artifactory_url}/${EXTERNAL_PACKAGES_NAME}"
  [[ $? -ne 0 ]] && bail "Error external package ${artifactory_url}/${EXTERNAL_PACKAGES_NAME} does not exist!"
  artifactory_path_exists "${artifactory_url}/${SWL_BUNDLE_NAME}"
  [[ $? -ne 0 ]] && bail "Error swl bundle ${artifactory_url}/${SWL_BUNDLE_NAME} does not exist!"
  echo "Will handle packages for ${SWL_DOWNLOAD_BUNDLE}!"
done

pull_release_area()
{
    local top_dir=${1?top_dir is required}
    local remote=${2?remote is required}
    local branch=${3?branch is required}
    local breed=$4

    local release_dir="${top_dir}/release"
    [ -n "${breed}" ] && release_dir="${release_dir}-${breed}"

    [ -d "${release_dir}" ] || mkdir -p "${release_dir}"

    echo "> creating $branch ${release_dir} area from $remote: $branch ..."
    pushd ${release_dir} >/dev/null
    git init . >/dev/null

    if git ls-remote $remote --exit-code &> /dev/null; then
        [ $? = 0 ] && git remote add origin $remote
        [ $? = 0 ] && git fetch --depth=1 origin $fetch_branch
        [ $? = 0 ] && git checkout -b $branch FETCH_HEAD
    fi

    if [ $? != 0 ]; then
        bail "unable to synchronize ${release_dir} area"
    fi

    popd
}

prepare_workarea() {
  local TOOLCHAIN_REMOTE="buic-scm:p1/project/otp-toolchain/release-sa515m"
  local HOST_REMOTE="buic-scm:p1/project/otp-host/release-generic"
  local OTP_VERSIONS_FILE="otp_versions.txt"
  download_artifacts "${WORKSPACE}" "${RELEASE_ID}" "${BASELINE_NAME}" "${OTP_VERSIONS_FILE}"

  source <(grep -E "OTP_HOST_VERSION=" ${OTP_VERSIONS_FILE})
  source <(grep -E "OTP_TOOLCHAIN_VERSION=" ${OTP_VERSIONS_FILE})

  if [[ -z ${OTP_HOST_VERSION} ]]; then
    echo "> Failed to parse HOST version using fallback version"
    OTP_HOST_VERSION="otp-host-3.426.3"
  fi

  if [[ -z ${OTP_TOOLCHAIN_VERSION} ]]; then
    echo "> Failed to parse Toolchain version using fallback version"
    OTP_TOOLCHAIN_VERSION="conmod-toolchain-sa515m-3.1.5.1"
  fi

  local SDK_ARTIFACTS=( "${STAGIN_DIR}/${SDK_BUNDLE_DIR}/sdk/sdk-constructor.tar.gz" "${STAGIN_DIR}/${SDK_BUNDLE_DIR}/sdk/sdk.tar.gz")
  local SDK_ARTIFACTS_PATHS=( "${WORKSPACE}" "${SDK_FS}")
  local SDK_ARTIFACTS_COUNT=${#SDK_ARTIFACTS[@]}
  local ENV_FILES=( "env-common" "env-target" "env-buildsys-static" )

  # 1) Setting up the environment
  header1 "Setting up the SDK Suite Environment for ${BASELINE_NAME}"

  header2 "Download SDK and extract SDK"
  echo "> mkdir '${STAGIN_DIR}'"
  mkdir "${STAGIN_DIR}"
  echo "> download_artifacts '${WORKSPACE}' '${RELEASE_ID}' '${BASELINE_NAME}/sdk' '${PKG_ZIP}'"
  download_artifacts "${WORKSPACE}" "${RELEASE_ID}" "${BASELINE_NAME}/sdk" "${PKG_ZIP}"
  echo "> unzip ${WORKSPACE}/${PKG_ZIP} -d ${STAGIN_DIR}"
  unzip ${WORKSPACE}/${PKG_ZIP} -d ${STAGIN_DIR}
  [[ $? -ne 0 ]] && bail "Unable to unzip ${PKG_ZIP}"

  # 4) Setup of SDK Suite
  header2 "Installing tar files"
  for (( c=0; c<SDK_ARTIFACTS_COUNT; c++ )); do
     [[ ! -d ${SDK_ARTIFACTS_PATHS[${c}]} ]] && bail "Unable to locate ${SDK_ARTIFACTS_PATHS[${c}]}"
     [[ ! -f ${SDK_ARTIFACTS[${c}]} ]]  && bail "Unable to find ${SDK_ARTIFACTS[${c}]}"
     echo "tar -zxf "${SDK_ARTIFACTS[${c}]}" -C ${SDK_ARTIFACTS_PATHS[${c}]}"
     tar -zxf "${SDK_ARTIFACTS[${c}]}" -C ${SDK_ARTIFACTS_PATHS[${c}]}
     RET_CODE=$((RET_CODE + $?))
     [ ${RET_CODE} -ne 0 ] && bail "Unable to unpacking ${SDK_ARTIFACTS[${c}]}"
  done

  pull_release_area ${WORKSPACE} ${TOOLCHAIN_REMOTE} ${OTP_TOOLCHAIN_VERSION} "toolchain"
  pull_release_area ${WORKSPACE} ${HOST_REMOTE} ${OTP_HOST_VERSION} "host"

  echo "Copy targetfs to toolchain"
  cp ${WORKSPACE}/.launchers/conmod-cm/swl/target-fsdir ${WORKSPACE}/release-toolchain/fs/devel/
  cp ${WORKSPACE}/.launchers/conmod-cm/swl/file_manifest.csv ${WORKSPACE}/release-toolchain/fs/devel/
}

prepare_workarea;

# Create tar function
create_tar () {
  echo "Workdir: $1"
  echo "Output file: $2"
  pushd $1 &> /dev/null
    TAR_FILES=$(ls -A)
    echo "tar --create --gzip --file $2 ${TAR_FILES[@]}"
    tar --create --gzip --file "$2" ${TAR_FILES[@]}
    [ $? -ne 0 ] && bail "Unable to updated $2"
  popd &> /dev/null
}

update_iso_tar() {
  IMAGE_SOURCE_DIR="$1"
  PACKAGE_LOOKUP_PATTERN="$2"
  IMAGE_NAME="$3"
  echo "Workdir: $IMAGE_SOURCE_DIR"
  echo "Target pattern: $PACKAGE_LOOKUP_PATTERN"
  echo "Image Name: ${IMAGE_NAME}"

  # Open ISO package
  PACKAGE_TAR="$(ls -t1 ${EXTRACTED_BLOCKS_DIR}/${PACKAGE_LOOKUP_PATTERN} | head -1)"
  header2 " Conti package Name: ${PACKAGE_TAR}"
  [[ -z "${PACKAGE_TAR}" ]] && bail "No iso package found"
  mkdir --parents ${EXTRACTED_ISOPKG_DIR}
  echo "> tar --extract --gzip --file ${PACKAGE_TAR} -C ${EXTRACTED_ISOPKG_DIR}"
  tar --extract --gzip --file "${PACKAGE_TAR}" -C ${EXTRACTED_ISOPKG_DIR}
  [ $? -ne 0 ] && bail "Unable to untar ${PACKAGE_TAR}"

  # Copying conti.iso into ISO Package
  [[ ! -f "${IMAGE_SOURCE_DIR}/${IMAGE_NAME}" ]] && bail "${IMAGE_SOURCE_DIR}/${IMAGE_NAME} not found"
  rsync --stats "${IMAGE_SOURCE_DIR}/${IMAGE_NAME}" "${EXTRACTED_ISOPKG_DIR}"

  # Updating new tar files
  # Updating conti package tar
  header2 "update ${PACKAGE_TAR}"
  create_tar "${EXTRACTED_ISOPKG_DIR}" "${PACKAGE_TAR}"

  echo "> rm -rf ${PACKAGE_TAR}"
  rm -rf "${EXTRACTED_ISOPKG_DIR}"
}

#no_of_files=$(get_number_of_files "${RELEASE_ID}" "${ESO_RELEASE}" "${WORKSPACE}")
for SWL_DOWNLOAD_BUNDLE in ${SWL_DOWNLOAD_BUNDLES[@]}
do
  #  TODO: remove test
  ESO_RELEASE="${SWL_DOWNLOAD_BUNDLE}/"
  download_artifacts "${WORKSPACE}" "${SWL_RELEASES}" "${ESO_RELEASE}"  "${EXTERNAL_PACKAGES_NAME}"
  # 6) Create External Package folder
  external_package_tar=${WORKSPACE}/${EXTERNAL_PACKAGES_NAME}
  header2 "Setup for Integrate eSo files for $SWL_DOWNLOAD_BUNDLE"
  echo "> Creating ${EXTERNAL_PACKAGES_DIR} folder"
  rm -rf ${EXTERNAL_PACKAGES_DIR}
  mkdir -p ${EXTERNAL_PACKAGES_DIR}

  # a) This external package should be renamed into something more generic
  #    for the benefit of this script.
  echo "> External Package Name: ${external_package_tar}"
  echo "> Untaring ${external_package_tar}"
  tar -xzf "${external_package_tar}" -C  "${EXTERNAL_PACKAGES_DIR}"
  RET_CODE=$((RET_CODE + $?))
  [ ${RET_CODE} -ne 0 ] && bail "Unable to untar ${external_package_tar}"

  # 6.1. Create /etc/internal_conti_testing to disable constant reboots
  touch ${EXTERNAL_PACKAGES_DIR}/etc/internal_conti_testing

  # 7) Generate images via SDK with eSolution part
  header2 "Generating images"
  echo "bash ${WORKSPACE}/.launchers/linux/sdk/install-prodfs-sdk --workspace ${WORKSPACE} --image_size 4K --signed_images ${WORKSPACE}/SDK-STAGING/${SDK_BUNDLE_DIR}/sdk/conti-signed-images.tar.gz"
  bash ${WORKSPACE}/.launchers/linux/sdk/install-prodfs-sdk --workspace "${WORKSPACE}" --image_size 4K --signed_images ${WORKSPACE}/SDK-STAGING/${SDK_BUNDLE_DIR}/sdk/conti-signed-images.tar.gz
  RET_CODE=$((RET_CODE + $?))
  [[ ${RET_CODE} -ne 0 ]] && bail "Unable to generate images"

  # a) Create copy of release folder for swdl-bundle
  echo "mkdir -p ${SWDL_IMAGE_DIR}"
  mkdir -p "${SWDL_IMAGE_DIR}"
  echo "rsync --stats -v ${CONTI_IMAGE_DIR}/* ${SWDL_IMAGE_DIR}"
  rsync --stats -v "${CONTI_IMAGE_DIR}"/* "${SWDL_IMAGE_DIR}"

  # 8) Execution of eSo Script
  header1 "Execution of eSolutions scripts"

  # a) Env variables for eSo Script
  echo "> Export of ESO environment variables"
  export CAS_WORKDIR="${WORKSPACE}"
  export CAS_HOSTFS="${WORKSPACE}/release-host/fs/host"

  # b) Script Execution
  echo "> Running set_env Script"
  if [[ -f "${SET_ENV_SCRIPT}" ]]; then
      ${SET_ENV_SCRIPT}
      [[ $? -ne 0 ]] && bail "Unable to call set_env script"
  else
      bail "${SET_ENV_SCRIPT} Not found"
  fi

  echo "> Running generate_swdl Script"
  if [[ -f "${ISO_GENERATION_SCRIPT}" ]]; then
      echo "> ${ISO_GENERATION_SCRIPT} -o ${WORKSPACE} -i ${CONTI_IMAGE_DIR} -s ${SDK_FS}/opt/conti/share/scripts/ "
      ${ISO_GENERATION_SCRIPT} -o ${WORKSPACE} -i ${CONTI_IMAGE_DIR} -s ${SDK_FS}/opt/conti/share/scripts/ 
      [[ $? -ne 0 ]] && bail "Unable to generate ISO Image"
  else
      bail "${ISO_GENERATION_SCRIPT} Not found"
  fi

  echo "END: Iso generation $SWL_DOWNLOAD_BUNDLE [${RET_CODE}]: $(date)"
  # ----------------------------------------------------------- #

  # Path verification
  [[ ! -d "${GENERATE_IMAGES_DIR}" ]] && bail "Unable to access to ${GENERATE_IMAGES_DIR}"

  #e)Prepare zip bundle - Taking the latest in the shared drive
  download_artifacts "${WORKSPACE}" "${SWL_RELEASES}" "${ESO_RELEASE}" "${SWL_BUNDLE_NAME}"
  eso_package_zip="${SWL_BUNDLE_NAME}"
  # Extracting ZIP Bundle
  header2 "Unzip eSo zip bundle: ${eso_package_zip}"
  rm -rf ${EXTRACTED_BUNDLE_DIR}
  unzip ${WORKSPACE}/${eso_package_zip} -d ${EXTRACTED_BUNDLE_DIR}
  [ $? -ne 0 ] && echo "Unable to unzip ${WORKSPACE}/${eso_package_zip}" && exit 1

  # Open swdl_blocks
  blocks="$(ls -t1 ${EXTRACTED_BUNDLE_DIR}/${BLOCKS_PATTERN} | head -1)"
  header2 " swdl_blocks package Name: ${blocks}"
  [[ -z ${blocks} ]] && bail "No swdl_blocks package found"
  rm -rf ${EXTRACTED_BLOCKS_DIR}
  mkdir --parents ${EXTRACTED_BLOCKS_DIR}
  echo "> tar --extract --gzip --file ${blocks} -C ${EXTRACTED_BLOCKS_DIR}"
  tar --extract --gzip --file "${blocks}" -C ${EXTRACTED_BLOCKS_DIR}
  [ $? -ne 0 ] && bail "Unable to untar ${blocks}"

  # Open ISO package
  header2 "Update general Conti block"
  update_iso_tar "${WORKSPACE}" "${CONTI_PACKAGE_TAR_PATTERN}" "General_Conti_Block.iso"
  header2 "Update modem Conti block"
  update_iso_tar "${WORKSPACE}" "${MODEM_PACKAGE_TAR_PATTERN}" "MCFG_Conti_Block.iso"

  # Updating block tar
  header2 "update ${blocks}"
  create_tar "${EXTRACTED_BLOCKS_DIR}" "${blocks}"

  # Update images folder
  header2 "updating image folder"
  BUNDLE_SUBFOLDER="$(ls -t1 ${EXTRACTED_BUNDLE_DIR} | head -1)"
  echo "> rsync --stats -v ${GENERATE_IMAGES_DIR}/* ${EXTRACTED_BUNDLE_DIR}/${BUNDLE_SUBFOLDER}/images/"
  rsync --stats -v "${GENERATE_IMAGES_DIR}"/* "${EXTRACTED_BUNDLE_DIR}/${BUNDLE_SUBFOLDER}/images/"

  # Versions
  HARMAN_RELEASE_VERSION="${SWL_DOWNLOAD_BUNDLE}"
  BASE_VERSION=$(echo ${BASELINE_NAME} | sed 's/.*-//g')

  # Copy disclaimer to BUNDLE_SUBFOLDER
  DISCLAIMER="!!!_Conti-internal_use_only_!!!.txt"
  echo "> cp ${WORKSPACE}/.launchers/conmod-cm/templates/${DISCLAIMER} ${EXTRACTED_BUNDLE_DIR}/${BUNDLE_SUBFOLDER}/${DISCLAIMER}"
  cp "${WORKSPACE}/.launchers/conmod-cm/templates/${DISCLAIMER}" "${EXTRACTED_BUNDLE_DIR}/${BUNDLE_SUBFOLDER}/${DISCLAIMER}"

  # Creating swl_test
  pushd ${EXTRACTED_BUNDLE_DIR} &> /dev/null
    if [[ ${BASELINE_NAME} =~ cl[0-9][0-9] ]]; then
      BUNDLE_NAME="${HARMAN_RELEASE_VERSION}-${BASH_REMATCH[0]}-${BASE_VERSION}.zip"
    else
      BUNDLE_NAME="${HARMAN_RELEASE_VERSION}-${BASE_VERSION}.zip"
    fi
    UPGRADE_BUNDLE="${WORKSPACE}/${BUNDLE_NAME}"
    echo "> zip --update --recurse-paths ${UPGRADE_BUNDLE} *"
    zip --update --recurse-paths "${UPGRADE_BUNDLE}" *
    [ $? -ne 0 ] && bail "Unable to create zip bundle ${UPGRADE_BUNDLE}.zip"
    upload_artifacts "${WORKSPACE}" "${RELEASE_ID}" "${BASELINE_NAME}/${SWL_TEST_UPGRADE}/" "${BUNDLE_NAME}"
    copy_artifact "${SWL_RELEASES}" "${SWL_DOWNLOAD_BUNDLE}/${eso_package_zip}" "${RELEASE_ID}" "${BASELINE_NAME}/${SWL_TEST_DOWNGRADE}/${HARMAN_RELEASE_VERSION}-raw.zip"
  popd &> /dev/null
done

echo "END: ${SCRIPT_NAME} [${RET_CODE}]: $(date)"
# ----------------------------------------------------------- #
